name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create Public Directory
      - name: Ensure Public Directory Exists
        run: mkdir -p public

      # Step 3: Generate Firebase Config File
      - name: Create Firebase Config File
        run: echo '${{ secrets.FIREBASE_CONFIG }}' > public/firebaseConfig.json

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
